---
- name: "Copy zipped archive"
  become: true
  synchronize:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
    recursive: true

- name: Creates directory
  file:
    path: ~/backend_app
    state: directory

- name: Extract the zipped artifact
  args:
    chdir: /home/ubuntu/backend_app
  shell: |
    pwd
    tar xzvf artifact.tar.gz
    ls -la

- name: "delete anything that might already be running"
  become: true
  ignore_errors: true
  command: pm2 delete all

- name: "start server"
  become: true
  args:
    chdir: /home/ubuntu/backend_app
  shell: pm2 start npm -- start
